import type { Metadata } from "next";
import "./globals.css";
import {Syne, DM_Mono} from "next/font/google"

const syne = Syne({
	variable: "--font-syne",
	subsets: ["latin"],
	weight: ["400", "600", "700", "800"],
});

const dmMono = DM_Mono({
	variable: "--font-dm-mono",
	subsets: ["latin"],
	weight: ["300", "400", "500"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${syne.variable} ${dmMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
